---
# This tasks modifies the quotas for the admin tenant to
# more suitable defaults as the resources for amphora
# provider are created in the "admin" tenant by default
- name: modify the quotas for the admin tenant to suit to production environments
  openstack.cloud.quota:
    name: "{{ admin_project_name | default('admin') }}"
    instances: "{{ num_amphora_instances }}"
    cores: "{{ num_amphora_cores }}"
    server_groups: "{{ num_amphora_server_groups }}"
    ram: "{{ amphora_ram_mb }}"
    port: "{{ num_amphora_ports }}"
    security_group: "{{ octavia_num_secgroup }}"
    security_group_rule: "{{ octavia_num_secgroup_rule }}"
    server_group_members: "{{ num_amphora_server_group_member }}"
    interface: admin
